### ISSUE TITLE
SE-8 Entregável I

### ISSUE THREAD

**Issue by jonh1036** [jonh1036/sistemaEntregas#9]
Vídeo de no máximo 5 minutos apresentando:

- [x] Linguagem/Framework desenvolvido;
- [x] Estrutura de Classes criadas;
- [x] Propriedades e Princípios aplicados.

**Comment by wendellsousadasilva** [comment]
Link vídeo: https://drive.google.com/file/d/117YS-yuBtXrD0f0jtpuZvKWs5cly4r4K/view?usp=drivesdk
